---
- hosts: all
  tasks:
  - name: install redis-server
    apt: name=redis-server state=present
    sudo: yes

  - name: enable redis-server to survive reboot
    service: name=redis-server enabled=yes

  - name: ensure redis is running
    service: name=redis-server state=started
    sudo: yes

  - name: install pip
    apt: pkg=python-pip state=present update_cache=yes cache_valid_time=300
    sudo: yes

  - name: install celery
    pip: name=celery
    sudo: yes

  - name: install redis python client
    pip: name=redis
    sudo: yes

  - name: run celery worker
    shell: celery -A tasks multi restart 5 --pidfile=celery%n.pid
    environment:
      PYTHONPATH: /vagrant/examples
      CELERY_BROKER: redis://
